apiVersion: v1
kind: Service
metadata:
  name: adtech-api-service
spec:
  selector:
    app: adtech-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  # 使用 LoadBalancer 模拟生产环境云服务入口
  type: LoadBalancer
